### PR TITLE
Regular layers

### PR DESCRIPTION
**Pull request by gebner**
This PR implements a refactoring of the expression classes, adding traits to expressions as determined by a (more or less) regular tree automaton (hence the name).

In short:  We now consider a data type of lambda expressions, where some lambda expressions are automatically assigned more specific types, for example being a FOLTerm.  These more specific types are implemented as traits, and they are assigned centrally (in the [determineTraits](https://github.com/gapt/gapt/blob/regular-layers/src/main/scala/at/logic/gapt/expr/traits.scala#L43-130) object).

The upshot of this is that equal expressions will always have the same types; Bottom() will always have a type that is a subtype of FOLFormula, whether you create it in the context of a propositional formula, or in the context of a HOL formula.

Other minor changes:
 * Bottom() and Top() are now logical constants, and *not* atoms.  This should prevent bugs like #315 and #309.

### CODE REVIEW

**Comment by mrukhaia** [comment]
Is this brunch already merged? Although the schemaprover brunch is not
finished yet, code compiles and tests are not failing, so I would like to
merge it in master before this brunch is merged.

Best regards
Mikheil Rukhaia

**Comment by shetzl** [comment]
Dear Mikheil,

The schemaprover branch is not yet ready to be merged into master:

1) Please follow Daniel's suggestion to avoid code duplication by deriving SchemaProofStrategy from (at least) PropositionalProofStrategy but better even from a to be newly created FirstOrderProofStrategy.

2) In my commit b74ef1259684b26b1c86a8d5331986fd619831d9 from May 1 I improved the solver by changing the invariant from proving the goal sequent to proving a subsequent of the goal sequent. This improves performance for propositional logic by about a factor of 20. Merging this with the current code in schemaprover will require some work.

The best strategy for avoiding a too large gap to the master branch is to periodically (e.g. once a week) merge master into your feature branch.

3) There is a number of smaller things that first have to be cleaned up, e.g. the println in commit 580def550af220aae1b13333d7005d3140d03ab2 or the log message  debug("running solvePropositional") at solve.scala:46 which should read something like "running schema prover".

Do you have time to participate in the gapt meeting next Wednesday, 14:45 via skype?

Best regards,
Stefan

3)

**Comment by mrukhaia** [comment]
Dear Stefan,

I'm not sure that I understood this sentence properly:

"The best strategy for avoiding a too large gap to the master branch is to
periodically (e.g. once a week) merge master into your feature branch."

Does it mean that I can merge master into schemaprover, not shemaprover to
master? I thought if I merge master into schemaprover, joining it back
would cause problems, when schemaprover brunch is finished.

I'll try my best to participate on the gapt meeting.

Best regards
Mikheil Rukhaia

**Comment by shetzl** [comment]
Dear Mikheil,

Yes, I really mean merging master into schemaprover. This will not at all cause problems when you finally merge schemaprover into master, on the contrary: it will make it easier because each single merge will create less conflicts.

Have a look, e.g., on the history of the regular-layers branch on https://github.com/gapt/gapt/network. There we have also used this strategy.

Best regards,
Stefan

**Comment by mrukhaia** [comment]
Nice, I did not know about it. Then it is not a problem, I'll merge master
into schemaprover and continue to work there.

Best regards
Mikheil Rukhaia

**Pull request merged**
