### PR TITLE
Tip examples

### PR DESCRIPTION
**Pull request by jannikvierling**

### CODE REVIEW

**Comment by gebner** [comment]
So to summarize, we currently parse TIP files in the following 4 steps:
 1. Run the tip tool on it. (For monomorphization and other stuff)
 2. Parse the resulting TIP file into an `SExpression` (`SExpressionParser`).
 3. Convert the `SExpression` into a `TIPProblem` (`TipSmtParser`).
 4. Convert the `TIPProblem` into a Context plus a goal (`TipProblem.ctx`, `TipProblem.toSequent`).

With the change in this PR, we would skip the first three steps for the TIP example proofs.  Each TIP example proof constructs a `TIPProblem` by hand, and then uses step 4 to convert it into a Context plus a goal to prove.  This fixes the immediate bug we have in issue #646: namely that the current TIP tool cannot parse the TIP files included in GAPT.

But I don't think it helps us much in the long run.  I think we should take this opportunity to also get rid of step 4 in the TIP example proofs.
  * We can then change the TIP import without breaking all the 65 example proofs.  Right now we can't even change the *order* of the formulas in the output without breaking them...  (This PR does not address this problem.)
  * We can get rid of hypothesis names like `h17` and replace them by something human-readable.

**Comment by jannikvierling** [comment]
If I understand well you say the formulas in the resulting sequent should be named manually for each example so that the formulas are not tied to their ordering in the definition and the names are more human-readable. Is that right? I am then not sure if we should keep the definition files so that we can reuse the problem definitions elsewhere or if we should integrate the problem definition into the proofs files.

**Comment by gebner** [comment]
> If I understand well you say the formulas in the resulting sequent should be named manually for each example so that the formulas are not tied to their ordering in the definition and the names are more human-readable. Is that right?

Yes, that's what I meant.

> I am then not sure if we should keep the definition files so that we can reuse the problem definitions elsewhere or if we should integrate the problem definition into the proofs files.

My preference would be to have them inline, like here for example:
https://github.com/gapt/gapt/blob/9fead5e9619846df8ab5c045e712cc48c1fb5531/examples/tip/prod/prop_01.scala#L10-L22

We can still use them from other files by referencing `prop_01.ctx` and `prop_01.sequent`, although I don't see where that would happen.

**Comment by gebner** [comment]
👍 I'm impressed. That's fast, and exactly how I think it should be.

**Comment by gebner** [comment]
@jannikvierling Do we also need to update the `testing/TIP/tip-benchmarks-0.2.tar.gz` file after this change?

**Comment by jannikvierling** [comment]
@gebner You're right I forgot about this file. There are also some examples in the user manual which use the TIP files and I don't yet know what I will do with these examples.

**Pull request merged**
